# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gNVK1HudBcxE0H4BN3PNP4Aozqq2CAWX
"""

TWITTER_CONSUMER_KEY = 'PfaP83YkexJ85BMD6ELbgox7a'
TWITTER_CONSUMER_SECRET = 'kiQVaZZ0s93RvW1HNVXd12qRmZzxJ2lKGfKX2hMyH49VqpeO01'
TWITTER_ACCESS_TOKEN = '33788959-7TvzbwimJX3NqH57pCAtVzZhuOmTry5MxEimJ2F8e'
TWITTER_ACCESS_TOKEN_SECRET = 'YxEACDGFgkS7MfOUmAj6MuTh41Ae0fG9QcnzpTxmBfXpY'

TWITTER_USERNAMES = [
                     'elonmusk',
                     'garyvee',
                     'saylor',
                     'dogecoin',
                     'CryptoYoda1338',
                     'Bitboy_Crypto'
]